<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Concerns\HasUuids;

class StatistikDokumen extends Model
{
    use HasFactory, SoftDeletes, HasUuids;

    protected $table = 'statistik_dokumen';

    protected $primaryKey = 'statistik_dokumen_id';

    public $incrementing = false;

    protected $keyType = 'string';

    protected $fillable = [
        'tahun',
        'bulan',
        'jumlah_kk',
        'jumlah_akte_lahir',
        'jumlah_akte_kematian',
        'jumlah_ktp',
        'jumlah_kia',
        'total_dokumen',
        'is_auto_generated',
        'generated_at',
    ];

    protected $casts = [
        'tahun' => 'integer',
        'bulan' => 'integer',
        'jumlah_kk' => 'integer',
        'jumlah_akte_lahir' => 'integer',
        'jumlah_akte_kematian' => 'integer',
        'jumlah_ktp' => 'integer',
        'jumlah_kia' => 'integer',
        'jumlah_pernikahan' => 'integer',
        'total_dokumen' => 'integer',
        'is_auto_generated' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    /**
     * Scope: Filter berdasarkan tahun
     */
    public function scopeTahun($query, int $tahun)
    {
        return $query->where('tahun', $tahun);
    }

    /**
     * Scope: Filter berdasarkan bulan
     */
    public function scopeBulan($query, int $bulan)
    {
        return $query->where('bulan', $bulan);
    }

    /**
     * Scope: Filter berdasarkan tahun dan bulan
     */
    public function scopePeriode($query, int $tahun, int $bulan)
    {
        return $query->where('tahun', $tahun)->where('bulan', $bulan);
    }

    /**
     * Scope: Hanya yang di-generate otomatis
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope: Urutkan dari periode terbaru
     */
    public function scopeTerbaru($query)
    {
        return $query->orderBy('tahun', 'desc')->orderBy('bulan', 'desc');
    }

    /**
     * Accessor: Nama bulan dalam bahasa Indonesia
     */
    public function getNamaBulanAttribute(): string
    {
        $namaBulan = [
            1 => 'Januari',
            2 => 'Februari',
            3 => 'Maret',
            4 => 'April',
            5 => 'Mei',
            6 => 'Juni',
            7 => 'Juli',
            8 => 'Agustus',
            9 => 'September',
            10 => 'Oktober',
            11 => 'November',
            12 => 'Desember',
        ];

        return $namaBulan[$this->bulan] ?? '';
    }

    /**
     * Accessor: Periode dalam format "Bulan Tahun"
     */
    public function getPeriodeFormattedAttribute(): string
    {
        return $this->nama_bulan . ' ' . $this->tahun;
    }

    /**
     * Accessor: Total dokumen formatted
     */
    public function getTotalDokumenFormattedAttribute(): string
    {
        return number_format($this->total_dokumen, 0, ',', '.');
    }

    /**
     * Accessor: Persentase KK
     */
    public function getPersentaseKkAttribute(): float
    {
        if ($this->total_dokumen == 0) return 0;
        return round(($this->jumlah_kk / $this->total_dokumen) * 100, 2);
    }

    /**
     * Accessor: Persentase Akte Lahir
     */
    public function getPersentaseAkteLahirAttribute(): float
    {
        if ($this->total_dokumen == 0) return 0;
        return round(($this->jumlah_akte_lahir / $this->total_dokumen) * 100, 2);
    }

    /**
     * Accessor: Persentase Akte Kematian
     */
    public function getPersentaseAkteKematianAttribute(): float
    {
        if ($this->total_dokumen == 0) return 0;
        return round(($this->jumlah_akte_kematian / $this->total_dokumen) * 100, 2);
    }

    /**
     * Accessor: Persentase KTP
     */
    public function getPersentaseKtpAttribute(): float
    {
        if ($this->total_dokumen == 0) return 0;
        return round(($this->jumlah_ktp / $this->total_dokumen) * 100, 2);
    }

    /**
     * Accessor: Persentase KIA
     */
    public function getPersentaseKiaAttribute(): float
    {
        if ($this->total_dokumen == 0) return 0;
        return round(($this->jumlah_kia / $this->total_dokumen) * 100, 2);
    }

    /**
     * Boot method untuk auto-calculate total
     */
    protected static function boot(): void
    {
        parent::boot();

        static::saving(function ($model) {
            // Auto-calculate total dokumen sebelum save
            $model->total_dokumen =
                ($model->jumlah_kk ?? 0) +
                ($model->jumlah_akte_lahir ?? 0) +
                ($model->jumlah_akte_kematian ?? 0) +
                ($model->jumlah_ktp ?? 0) +
                ($model->jumlah_kia ?? 0);
        });
    }
}

